@startuml Database-structure



object utasok{
   <u>utasazon
    nev
    szulnev
    szulho
    szulnap
    kor
    nem
    igtipus
    igszam
    tel
    email
    orszag
    irszam
    varos
    utca
    erttel
    ertemail
    biztnev
    fizmod
    aktiv
}

object utazas{
    utazasazon*
    <u>utasazon
    honnan
    celpont*
    <u>mettol
    meddig
    utazasmod
    ellatas
    ar
    aktiv

}

object userdata {
    <u>utasid
    email
    jelszo
}

object csoport{
    <u>utasid
    <u>utazasid
    csoportid
}

object helyszin {
    <u>nev
    varos
    <u>cim
    minoseg
    leiras
    csillag
    aktiv
}

object csomagok {
    <u>csomagid
    honnan
    celpont*
    mettol
    meddig
    utazasmod
    ellatas
    ar
    aktiv
}

object szolgaltatasok {
    <u>nev
    sajat_furdo
    terasz
    franciaagy
    gyerekbarat
    ac
    konyha
    parkolas
    tv
    gym
    medence
    bar
    internet
    szef
    akadalymentes
}


utasok::utasazon -up- utazas::utasazon
utasok::utasazon -right- userdata::utasid
csoport::utasid -right- utasok::utasazon
csoport::utazasid --- utazas::utazasazon
helyszin::nev --- utazas::celpont
csomagok::celpont -left- helyszin::nev
szolgaltatasok::nev -left- helyszin::nev

map legend {
    alahuzas => primary key
    * => foreign key
     
}

@enduml